import type { BootstrapPhase } from "../../contracts/bootstrap-phase";

/* =============================================================================
 * Execution Plan
 * =============================================================================
 *
 * Immutable execution blueprint generated by PipelineBuilder.
 *
 * The ExecutionPlan is the single source of truth consumed by the
 * PipelineExecutor.
 *
 *
 * Responsibilities
 * ---------------------------------------------------------------------------
 *
 * • Preserve ordered bootstrap phases
 * • Provide deterministic execution sequence
 * • Expose plan metadata
 * • Allow execution diagnostics
 *
 *
 * Does NOT:
 *
 * • execute phases
 * • validate phase logic
 * • resolve executors
 * • mutate runtime state
 *
 *
 * Lifecycle:
 *
 *
 * BootstrapPhasesCatalog
 *          |
 *          v
 *   PipelineBuilder
 *          |
 *          v
 *   ExecutionPlan
 *          |
 *          v
 * PipelineExecutor
 *
 *
 * =============================================================================
 */

export interface ExecutionPlan {
  /**
   * Unique execution plan identifier.
   *
   * Used for:
   *
   * • tracing
   * • diagnostics
   * • telemetry
   */
  readonly id: string;

  /**
   * ---------------------------------------------------------------------------
   * Ordered bootstrap phases.
   *
   * The order is already resolved by PipelineBuilder.
   *
   * Consumers must execute sequentially.
   *
   * ---------------------------------------------------------------------------
   */
  readonly phases: readonly BootstrapPhase[];

  /**
   * ---------------------------------------------------------------------------
   * Number of executable phases.
   *
   * ---------------------------------------------------------------------------
   */
  readonly size: number;

  /**
   * ---------------------------------------------------------------------------
   * Plan creation timestamp.
   *
   * Used for diagnostics and instrumentation.
   *
   * ---------------------------------------------------------------------------
   */
  readonly createdAt: Date;

  /**
   * ---------------------------------------------------------------------------
   * Optional execution metadata.
   *
   * Reserved for:
   *
   * • tracing
   * • profiling
   * • telemetry
   * • debugging tools
   *
   * ---------------------------------------------------------------------------
   */
  readonly metadata: Readonly<Record<string, unknown>>;
}
